### ISSUE TITLE
講習の目的との内容の整合について

### ISSUE THREAD

**Issue by r-kurose** [RTC-Library-FUKUSHIMA/Education#9]
文書「標準ソフトウェア(OpenRTM)による ロボットプログラミング」 の P.4 に、
「ロボット制御の基礎となるC言語を用いた マイコンプログラミング技術」 が
目的として掲げられている。
一方で、 内容については Python のみの利用に見え、目的が果たされていないように見える。

**Comment by rtc-fukushima** [comment]
ご指摘ありがとうございます。
このテキストは「ロボット関連人材育成研修」内の30時間分のテキストであり、
「ROS・RTMを用いた実践的なロボットプログラミング技術を習得」を目的としております。
「ロボット制御の基礎となるC言語を用いた マイコンプログラミング技術」は別の所でカバーしております。
「ロボット関連人材育成研修」全体は以下を参照してください。
https://www.pref.fukushima.lg.jp/sec/32021e/robo-jinzai-ikusei-31.html

**Comment by r-kurose** [comment]
二部構成の片側ということだったのですね。
ありがとうございました。
